# Generated by Django 5.2.1 on 2025-05-21 04:05

from django.db import migrations


def add_default_sizes_colors(apps, schema_editor):
    # Get the Size and Color models from the app registry
    Size = apps.get_model('inventory', 'Size')
    Color = apps.get_model('inventory', 'Color')
    
    # Add default sizes if they don't exist
    default_sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    for size_name in default_sizes:
        if not Size.objects.filter(name=size_name).exists():
            Size.objects.create(name=size_name)
    
    # Add default colors if they don't exist
    default_colors = [
        {'name': 'Black', 'color_code': '#000000'},
        {'name': 'White', 'color_code': '#FFFFFF'},
        {'name': 'Red', 'color_code': '#FF0000'},
        {'name': 'Blue', 'color_code': '#0000FF'},
        {'name': 'Green', 'color_code': '#008000'},
        {'name': 'Yellow', 'color_code': '#FFFF00'},
        {'name': 'Purple', 'color_code': '#800080'},
        {'name': 'Pink', 'color_code': '#FFC0CB'},
        {'name': 'Gray', 'color_code': '#808080'},
        {'name': 'Brown', 'color_code': '#A52A2A'},
    ]
    
    for color_data in default_colors:
        if not Color.objects.filter(name=color_data['name']).exists():
            Color.objects.create(**color_data)


def remove_default_sizes_colors(apps, schema_editor):
    # Get the Size and Color models from the app registry
    Size = apps.get_model('inventory', 'Size')
    Color = apps.get_model('inventory', 'Color')
    
    # Remove default sizes
    default_sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    Size.objects.filter(name__in=default_sizes).delete()
    
    # Remove default colors
    default_color_names = ['Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Pink', 'Gray', 'Brown']
    Color.objects.filter(name__in=default_color_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default_sizes_colors,
            remove_default_sizes_colors
        ),
    ]
