# Generated by Django 5.2.1 on 2025-05-21 04:04

from django.db import migrations


def add_default_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('products', 'Category')
    
    # Add default categories if they don't exist
    default_categories = [
        {'name': 'T-shirt', 'description': 'Short-sleeved casual tops'},
        {'name': 'Cropped Shirt', 'description': 'Shorter length shirts with stylish cuts'},
    ]
    
    for category_data in default_categories:
        if not Category.objects.filter(name=category_data['name']).exists():
            Category.objects.create(**category_data)


def remove_default_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('products', 'Category')
    
    # Remove default categories
    default_category_names = ['T-shirt', 'Cropped Shirt']
    Category.objects.filter(name__in=default_category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default_categories,
            remove_default_categories
        ),
    ]
