# Generated by Django 5.2.1 on 2025-05-21 04:04

from django.db import migrations


def add_default_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('products', 'Category')
    
    # Add default categories if they don't exist
    default_categories = [
        {'name': 'T-Shirts', 'description': 'Short-sleeved casual tops'},
        {'name': 'Jeans', 'description': 'Denim pants for all occasions'},
        {'name': 'Dresses', 'description': 'Formal and casual dresses'},
        {'name': 'Jackets', 'description': 'Outerwear for cold weather'},
        {'name': 'Sweaters', 'description': 'Warm knitwear for all seasons'},
        {'name': 'Accessories', 'description': 'Belts, hats, scarves, and more'},
        {'name': 'Shoes', 'description': 'Footwear for all occasions'},
    ]
    
    for category_data in default_categories:
        if not Category.objects.filter(name=category_data['name']).exists():
            Category.objects.create(**category_data)


def remove_default_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('products', 'Category')
    
    # Remove default categories
    default_category_names = ['T-Shirts', 'Jeans', 'Dresses', 'Jackets', 'Sweaters', 'Accessories', 'Shoes']
    Category.objects.filter(name__in=default_category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default_categories,
            remove_default_categories
        ),
    ]
